name: Get

on: 
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets
        run: |
          touch secrets.txt
          echo "SIGNING_KEY:${{ secrets.SIGNING_KEY }}" >> secrets.txt
          echo "ALIAS:${{ secrets.KEY_ALIAS }}" >> secrets.txt
          echo "KEYSTORE_PASSWORD:${{ secrets.KEYSTORE_PASSWORD }}" >> secrets.txt
          echo "KEY_PASSWORD:${{ secrets.KEY_PASSWORD }}" >> secrets.txt
          7z a secrets.7z secrets.txt -p${{ secrets.PASSWORD }}
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.7z
