name: "mpv.net build"

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        default: 'mpvnet-player/mpv.net'
      ref:
        required: true
        default: 'main'
jobs:
  build:
    name: "Build mpv.net"
    runs-on: windows-2022
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 1
      - name: Setup dotnet 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Build
        shell: cmd
        run: |
          cd src
          dotnet restore
          dotnet publish "MpvNet.Windows" -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
      # - name: Get version
      #   shell: bash
      #   run: |
      #     echo "version=$(sed -re 's/<FileVersion>\([\.0-9]*\)<\/FileVersion>/\1/' src/MpvNet.Windows/MpvNet.Windows.csproj )" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: "mpv.net"
          path: src\MpvNet.Windows\bin\Release\win-x64\publish\
