name: "mpv.net build"

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        default: 'mpvnet-player/mpv.net'
      ref:
        required: true
        default: 'main'
jobs:
  build:
    name: "Build mpv.net"
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build
        shell: cmd
        run: |
          cd src
          nuget restore
          msbuild -restore
          msbuild MpvNet.sln /m /p:Configuration=Release
      - name: Get version
        shell: bash
        run: |
          echo "version=$(sed -e 's/<FileVersion>(.*)<\/FileVersion>/\1/' src/MpvNet.Windows/MpvNet.Windows.csproj )" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: "mpv.net_${{ env.version }}"
          path: src/MpvNet.Windows/bin/Release/
